### ISSUE TITLE
Cannot install on Mac ARM64 (Apple Sillicon)

### ISSUE THREAD

**Issue by jmpfar** [gregorias/pycodec2#37]
## Checklist

Complete this checklist before filing the bug ticket:

- [X] I have verified that I'm using [compatible](https://github.com/gregorias/pycodec2#codec-2-compatibility) Pycodec2 and Codec2 versions.

## Bug description

When installing pycodec2 on mac, there's a failure while installing the wheel:

```shell
$ pip install pycodec2
Collecting pycodec2
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Users/my.user/Downloads/pycodec2-3.0.1/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/my.user/Downloads/pycodec2-3.0.1/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/my.user/Downloads/pycodec2-3.0.1/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 29, in <module>
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/vh/2xf8thqd3572vjfgnnzvx1_m0000gn/T/pip-build-env-1cza6wjg/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pycodec2/pycodec2.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

## Reproduction steps

1. Install codec2 on Mac Apple Sillicon using brew
2. Run `pip install pycodec2`

## Expected behavior

Wheel is installed

## Additional information

- OS version: macOS 15.1
- Codec2 version: 1.2.0
- Pycodec2 version: 3.0.1

## Additional context

There are two issues here:
1. There are no wheels being built for MacOS arm64, it seems that this can be relatively easily fixed by using a newer macos builder in github actions
2. The source distribution has issues with missing files, my guess due to the `MANIFEST.in` configuration:

When adding the following lines to the manifest:
```
include pycodec2/pycodec2.pyx
include pycodec2/codec2.pxd
```

pip install now fails on a different error:
```
      pycodec2/pycodec2.c:1253:10: fatal error: 'codec2/codec2.h' file not found
       1253 | #include "codec2/codec2.h"
            |          ^~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

This can probably be fixed as you do in the CI by installing the library from source, or instead adding the brew paths to the environment:

```shell
CPATH=/opt/homebrew/Cellar/codec2/1.2.0/include:$CPATH LIBRARY_PATH=/opt/homebrew/Cellar/codec2/1.2.0/lib:$LIBRARY_PATH pip install .
```

Which finally gets everything built correctly

**Comment by gregorias** [comment]
I’ve released 3.0.3 with the fixes.
